### ISSUE TITLE
Fresh docker-compose install won't start when supplying the "branch" environment variable

### ISSUE THREAD

**Issue by cewert** [Organizr/docker-organizr#20]
I am setting up a new install of organizr using the following docker-compose config:

```organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=988
      - PGID=987
      - fpm="false" # use socket connections instead of TCP
      - branch="v2-master"
    volumes:
      - /xxx/xxx/xxx:/config
    ports:
      - 80:80
    network_mode: "xxx"
    restart: unless-stopped
```

...but organizr fails to start with the following error: 
```

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-setup: executing... 
[cont-init.d] 30-setup: exited 0.
[cont-init.d] 40-install: executing... 
"v2-master" is not a valid branch, exiting
[cont-init.d] 40-install: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting
```

To get my install working I just commented out the branch variable like so:

```
organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=988
      - PGID=987
      - fpm="false" # use socket connections instead of TCP
      #- branch="v2-master"
    volumes:
      - /xxx/xxx/xxx:/config
    ports:
      - 80:80
    network_mode: "xxx"
    restart: unless-stopped
```

**Comment by Roxedus** [comment]
Your quotes are wrong. You have to quote the whole key-value pair when using that compose syntax.

**Comment by cewert** [comment]
Ahh good call. Thank you!

For anyone that stumbles on this in the future, here's my now working config:

```
organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=988
      - PGID=987
      - fpm=false # use socket connections instead of TCP
      - TZ=America/New_York
      - branch=v2-master #valid values are v2-master, master, v2-develop, develop
    volumes:
      - /xxx/xxx/xxx:/config
    ports:
      - 80:80
    network_mode: "xxx"
    restart: unless-stopped
```
