### ISSUE TITLE
Startup loop on macos

### ISSUE THREAD

**Issue by foozmeat** [Organizr/docker-organizr#31]
My docker-compose block looks like

```
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      fpm: true
      branch: v2-develop
    volumes:
        - ./config/organizr:/config
    ports:
      - 8888:80
    restart: unless-stopped
```

When the container boots I run into the following error 
```
organizr  | -------------------------------------
organizr  | GID/UID
organizr  | -------------------------------------
organizr  | User uid:    501
organizr  | User gid:    501
organizr  | -------------------------------------
organizr  | 
organizr  | 
organizr  | [cont-init.d] 10-adduser: exited 0.
organizr  | [cont-init.d] 20-config: executing... 
organizr  | [cont-init.d] 20-config: exited 0.
organizr  | [cont-init.d] 30-setup: executing... 
organizr  | chown: changing ownership of '/config/www/organizr/.git/objects/pack/pack-9fe38f44429019bc9f2de7378346b06321b2c5c1.idx': Permission denied
organizr  | chown: changing ownership of '/config/www/organizr/.git/objects/pack/pack-9fe38f44429019bc9f2de7378346b06321b2c5c1.pack': Permission denied
organizr  | chmod: changing permissions of '/config/www/organizr/.git/objects/pack/pack-9fe38f44429019bc9f2de7378346b06321b2c5c1.idx': Permission denied
organizr  | chmod: changing permissions of '/config/www/organizr/.git/objects/pack/pack-9fe38f44429019bc9f2de7378346b06321b2c5c1.pack': Permission denied
organizr  | [cont-init.d] 30-setup: exited 0.
organizr  | [cont-init.d] 40-install: executing... 
```

and then the container restarts and the loop continues. This seems to be caused by using the VirtioFS driver. See this related issue: https://github.com/causefx/Organizr/issues/1907

If `40-install` simply didn't try and change permissions on /config I think we could avoid this issue. It seems incorrect to use `chown -R abc:abc` when we're passing in a preferred UID/GID.
