### ISSUE TITLE
Docker container not starting on arm64

### ISSUE THREAD

**Issue by sametjan** [Organizr/docker-organizr#7]
I'm trying to get this image running on my QNAP server, but whenever I try to start the container all I get is `standard_init_linux.go:185: exec user process caused "exec format error"`

From my docker-compose file:
```yaml
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    restart: always
    ports:
      - "80:80"
    volumes:
      -<path>:/config
    env_file:
      - ./shared.env
```

I've tried both the `latest` and `arm64` tags, but still get the same error in my log.

**Comment by Roxedus** [comment]
Whats the actual CPU arch on that QNAP? `uname -a`

**Comment by sametjan** [comment]
`Linux HomeNAS 4.2.8 #2 SMP Sat Oct 24 09:15:05 CST 2020 aarch64 GNU/Linux`

**Comment by Roxedus** [comment]
I spotted some inconsistencies in the manifest, I have now redone that part of the build-process. Does it still behave like this on the latest image?

**Comment by sametjan** [comment]
Yeah, I'm still getting the same message on the latest image.

**Comment by christronyxyocum** [comment]
Wait, what version of Docker is installed? `docker -v`

**Comment by sametjan** [comment]
`Docker version 17.09.1-ce, build 0bbe3ac`

**Comment by christronyxyocum** [comment]
And what version of compose do you have specified at the top of your `docker-compose.yml` file?

**Comment by sametjan** [comment]
3.6

**Comment by christronyxyocum** [comment]
That could be it. Can you try creating a separate compose file in another directory for just the Organizr container and setting the version first to `3.4` and, if that doesn't work, try `2.4`?

**Comment by Roxedus** [comment]
What about the new non-manifested build? `organizr/organizr:linux-arm64`

**Comment by sametjan** [comment]
Tried `3` and `2.4`, using `organizr/organizr:linux-arm64` and still no luck.

**Comment by sametjan** [comment]
I finally got a working version. Cloned this repo, and had my docker-compose build the image locally, setting the `BASE_IMAGE` to `organizr/base:latest`.

```yaml
  organizr:
    build:
      context: <path>docker-organizr
      args:
        BASE_IMAGE: organizr/base:latest
    container_name: organizr
    restart: always
    ports:
      - "80:80"
    volumes:
      - <path>:/config
    env_file:
      - ./shared.env
    environment:
      fpm: "true"
      branch: "v2-master"
```
